### ISSUE TITLE
 Source code 

### ISSUE THREAD

**Issue by Youskrpig** [yxgeee/SDA#1]
when will the source code be released?

**Comment by yxgeee** [comment]
Sorry for the delay due to the fact that the paper is still in submission. Another version of SDA code can be found at https://github.com/yxgeee/MMT-plus/tree/master/visda/sda, which was used in the VisDA-2020 Challenge. There are a few differences from the original paper but can be referred to.

**Comment by Youskrpig** [comment]
Thanks a lot!
